# This docker-compose file will spin up an ACS cluster on a local host or on a server and it requires a minimum of 12GB Memory to distribute among containers.
# Limit container memory and assign X percentage to JVM.  There are couple of ways to allocate JVM Memory for ACS Containers
# For example: 'JAVA_OPTS: "$JAVA_OPTS -XX:+PrintFlagsFinal -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
# But, as per Oracle docs (https://docs.oracle.com/javase/9/gctuning/parallel-collector1.htm#JSGCT-GUID-CAB83393-3438-44ED-98F0-D15641B43C7D)
# If container memory is not explicitly set, then the above flags will default max heap to 1/4th of container's memory which may not be ideal.
# Hence, setting up explicit Container memory and then assigning a percentage of it to the JVM for performance tuning.

# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "3.5"

services:
  redmine:
    image: redmine:4.0.4-alpine
    container_name: redmine
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_POSTGRES: db-redmine
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: password
      RAILS_RELATIVE_URL_ROOT: /redmine
    restart: always
    depends_on:
      - db-redmine
    volumes:
      - /opt/redmine/files:/usr/src/redmine/files
      - /opt/redmine/log:/usr/src/redmine/log
      - /opt/redmine/plugins:/usr/src/redmine/plugins
      - /opt/redmine/public/themes:/usr/src/redmine/public/themes
      - /opt/redmine/redmine_config.ru:/usr/src/redmine/config.ru
    links:
      - db-redmine
    networks:
      - container-link

  db-redmine:
    image: postgres:12-alpine
    container_name: postgres_redmine
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_ROOT_PASSWORD: postgres
      REDMINE_DB_DATABASE: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - /opt/redmine/db/data:/var/lib/postgresql/data
      - /opt/redmine/db/initdb:/docker-entrypoint-initdb.d
    networks:
      - container-link

  alfresco:
    image: alfresco/alfresco-content-repository-community:6.1.2-ga
    #mem_limit: 1500m
    container_name: alfresco
    environment:
      JAVA_OPTS : "
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://db-alfresco:5432/alfresco
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.secureComms=none
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dshare.host=localhost
        -Dalfresco.port=8082
        -Daos.baseUrlOverwrite=http://localhost:8082/alfresco/aos
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false
        -Xms2g -Xmx2g
        "
    volumes:
            #      - alfresco-data:/usr/local/tomcat/alf_data
      - /opt/alfresco/data:/usr/local/tomcat/alf_data
    ports:
      - 8082:8080 #Browser port
    depends_on:
      - db-alfresco
    networks:
      - container-link

  share:
    image: alfresco/alfresco-share:6.1.0-RC3
    container_name: share
    #mem_limit: 1g
    environment:
      - REPO_HOST=alfresco
      - REPO_PORT=8080
      - "CATALINA_OPTS= -Xms500m -Xmx500m"
    ports:
      - 8080:8080
    depends_on:
      - alfresco
    networks:
      - container-link

  db-alfresco:
    image: postgres:12-alpine
    container_name: postgres_alfresco
    #mem_limit: 1500m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - /opt/alfresco/db/data:/var/lib/postgresql/data
      - /opt/alfresco/db/initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - container-link

  solr6:
    image: alfresco/alfresco-search-services:1.3.0-RC2
    container_name: solr6
    #mem_limit: 2500m
    environment:
      #Solr needs to know how to register itself with Alfresco
      - SOLR_ALFRESCO_HOST=alfresco
      - SOLR_ALFRESCO_PORT=8080
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=solr6
      - SOLR_SOLR_PORT=8983
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
      - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
    ports:
      - 8083:8983 #Browser port
    depends_on:
      - alfresco
    networks:
      - container-link

  activemq:
    image: alfresco/alfresco-activemq:5.15.6
    container_name: activemq
    #mem_limit: 2048m
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP
    depends_on:
      - alfresco
    networks:
      - container-link

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /opt/nginx/nginx_reverseproxy.conf:/etc/nginx/nginx.conf:ro
    links:
      - redmine
      - alfresco
      - share
      - solr6
    networks:
      - container-link

networks:
  default:
    external: true
  container-link:
    external: false

    #volumes:
    #  alfresco-data:
    #    name: alfresco-data
    #    driver: local


